version: "3"
services:
  postgres_sorteador_db: 
    image: postgres
    container_name: postgres_sorteador_db
    restart: always
    ports:
      - 5431:5432
    env_file: 
      - back-end/.env.test
    volumes:
      - pg_sorteador-db:/var/lib/postgresql/data

  node_sorteador_app:
    container_name: node_sorteador_app
    build: ./back-end
    image: node_sorteador_app_image
    ports: 
      - 3000:5000
    depends_on:
      - postgres_sorteador_db
    env_file:
      - back-end/.env.test